[build]
publish = "public"
command = """tinacms build && hugo \
  --config config.toml \
  --themesDir themes \
  --theme hugo-geekdoc """

[build.environment]
HUGO_VERSION = "0.82.1"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

## This rule redirects to an external API, signing requests with a secret
[[redirects]]
  from = "/"
  to = "https://rawrrdocs.conexo.org/es"
  status = 301
  force = true # COMMENT: ensure that we always redirect
  headers = {X-From = "Netlify"}
