[build]
publish = "public"
command = """tinacms build && hugo \
  --config config.toml \
  --themesDir themes \
  --theme hugo-geekdoc """

[build.environment]
HUGO_VERSION = "0.102.3"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[[redirects]]
  from = "/es/en"
  to = "/en"
  status = 301
  force = true