---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: directory
  path: docs/en/content
  label: "(en) Init Page"
  create: all
  match: "*"
- type: directory
  path: docs/content/en/1 Introduction
  label: "(en) Introduction"
  create: all
  match: "**/*"
- type: directory
  path: docs/content/en/2 Usage
  label: "(en) Usage"
  create: all
  match: "**/*"
- type: directory
  path: docs/content/en/3 Functions
  label: "(en) Functions"
  create: all
  match: "**/*"
- type: directory
  path: docs/content/es
  label: "(es) Página de inicio"
  create: all
  match: "*"
- type: directory
  path: docs/content/es/1 Introducción
  label: "(es) Introducción"
  create: all
  match: "**/*"
- type: directory
  path: docs/content/es/2 Uso
  label: "(es) Uso"
  create: all
  match: "**/*"
- type: directory
  path: docs/content/es/3 Funciones
  label: "(es) Funciones"
  create: all
  match: "**/*"
upload_dir: docs/static/images/en
public_path: "/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.81.0
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: hugo server -D -E -F --renderToDisk -d public
version: 0.81.0
